version: "3"
services:
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    expose:
      - "2181"
    tmpfs: "/datalog"
    volumes:
      - ~/kafka/data/zookeeper_data:/var/lib/zookeeper/data
      - ~/kafka/data/zookeeper_log:/var/lib/zookeeper/log
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    expose:
      - "9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./.env
    depends_on:
      - zookeeper
  web_service:
    build: ./web_service
    container_name: web_service
    #context: ./server/
    command: /usr/app/node_modules/.bin/nodemon src/server.js
    volumes:
      - ./web_service:/usr/app
      - /usr/app/node_modules
    expose:
      - "8080"
    env_file: ./.env
    depends_on:
      - mongo
  hubspot_service:
    build: ./hubspot_service
    container_name: hubspot_service
    #context: ./server/
    command: /usr/app/node_modules/.bin/nodemon src/server.js
    volumes:
      - ./hubspot_service:/usr/app
      - /usr/app/node_modules
    expose:
      - "8080"
    env_file: ./.env
    depends_on:
      - mongo
  client:
    build: ./client
    container_name: idea_tracker_client
    #context: ./client/
    #command: yarn start
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    depends_on:
      - web_service
    ports:
      - "3000:3000"
    env_file: ./.env
  mongo:
    # upgrade to https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3 later
    image: mongo
    container_name: idea_tracker_database
    volumes:
      - ./mongo-volume:/data/db
    expose:
      - "27017"
volumes:
  web_service:
  hubspot_service:
  client:
  mongo:
